language: node_js

notifications:
  email: false

node_js:
  - "12.16.2"

install: npm install

jobs:
  include:
    - stage: Tests
      if: |
        branch = develop AND \
        tag IS blank AND \
        commit_message !~ /(no-deploy|wip)/
      script:
        - npm run lint
        - npm run test:e2e
      after_success:
        - wget https://raw.githubusercontent.com/retyp/travis-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $DISCORD_WEBHOOK_URL
      after_failure:
        - wget https://raw.githubusercontent.com/retyp/travis-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $DISCORD_WEBHOOK_URL

cache:
  directories:
    - node_modules