language: node_js

notifications:
  email: false

node_js:
  - "12.16.2"

install: npm install

jobs:
  include:
    - stage: Tests
      if: |
        branch = develop AND \
        tag IS blank AND \
        commit_message !~ /(no-deploy|wip)/
      script: 
        - npm run lint
        - npm run test:e2e

cache:
  directories:
    - node_modules