language: node_js

notifications:
  email: false

node_js:
  - "12.16.2"

before_install:
  - openssl aes-256-cbc -K $encrypted_55ecc9189931_key -iv $encrypted_55ecc9189931_iv
    -in deploy_rsa.enc -out .travis/deploy_rsa -d

install: npm install

jobs:
  include:
    - stage: Tests
      if: |
        branch = develop AND \
        tag IS blank AND \
        commit_message !~ /(no-deploy|wip)/
      script:
        - npm run lint
        - npm run test:e2e

    # Build and push both current version & latest version
    - stage: Build Docker image
      if: branch = master
      script:
      - "PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - echo "==============================================="
      - echo "==== Building retyp/front:$PACKAGE_VERSION ===="
      - echo "==============================================="
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t retyp/front .
      - docker tag retyp/front retyp/front:current
      - docker tag retyp/front retyp/front:${PACKAGE_VERSION}
      - docker push retyp/front:current
      - docker push retyp/front:${PACKAGE_VERSION}

    # Deploy latest API version
    - stage: Deploy
      if: branch = master
      script:
        - sh .travis/deploy.sh

cache:
  directories:
    - node_modules